### ISSUE TITLE
Upload .csv option is throwing a fatal error

### ISSUE THREAD

**Issue by chawlamark** [SuraManasa/Voluteer-Reg#18]
**_Description_** 
System is throwing a fatal error when a corporate user tries to register for shifts without uploading a list of volunteers as a .csv file.
_**Related Test Case**_  
T2.02b ( Refer to Test Report)
**Priority:** High
_**_Error/Issue_**_ 
![image](https://user-images.githubusercontent.com/75512097/102654642-e2931580-413e-11eb-9151-103f8eb9b554.png)

_**Expected Results**_
System must allow corporate users to manually add the list of volunteers if they choose not to upload a .csv file 
_**Steps to Reproduce:**_
- A corporate user logs in 
- Proceeds to register for shift without uploading a .csv file 
- System throws a fatal error.

**Comment by SuraManasa** [comment]
Code changes for handling this scenario(when no csv is uploaded) is done.
Now if we try to register without uploading any csv its shows an empty volunteer table with out showing an error
