### ISSUE TITLE
Invalid Dates 

### ISSUE THREAD

**Issue by chawlamark** [SuraManasa/Voluteer-Reg#2]
**_Description_** 
System is allowing invalid shifts containing invalid dates to be registered. Registered shifts can have a past date or time. 
_**Related Test Case**_  
T1.01b ( Refer to Test Report)
**_Priority:_** High 
_**_Error/Issue_**_ 
![image](https://user-images.githubusercontent.com/75512097/101232352-44537a00-367f-11eb-8a17-6b9b319794ab.png)
_**Expected Results**_
System must generate an error in case of invalid input. 
_**Steps to Reproduce:**_
- An admin/organization user logs in 
- Enters input to add shifts and selects an invalid date in the past. 
- Continues to add shift using the add button

**Comment by SuraManasa** [comment]
Code changes implemented to handle this issue
