### ISSUE TITLE
Confirm Password field doesn't work 

### ISSUE THREAD

**Issue by chawlamark** [SuraManasa/Voluteer-Reg#9]
**_Description_** 
System is not checking if the user is entering the same password in the 'confirm password' field on registration form of any user type.
_**Related Test Case**_  
T 5.01a ( Refer to Test Report)
**_Priority_** : Low  
_**_Error/Issue_**_ 
Confirm Password field on account registration forms is dysfunct. 
_**Expected Results**_
System must check if the user is entering same password twice 
_**Steps to Reproduce:**_
User navigates to registration form.
Enters any invalid input in confirm password field. 
System still allows account creation and updates the database.

**Comment by SuraManasa** [comment]
Implemented code changes
